export const experienceList = [
  ["System Administrator",
    "2000 - 2003",
    "Garmix Bt",
    "System administrator, web store operator (OsCommerce, Prestashop), inventory manager, connection builder."],
  ["Sales Manager",
    "2000 - 2003",
    "Garmix Bt",
  "Salesman, purchaser, relationship manager."],
  ["Customer Support Specialist",
  "2011 - 2012",
  "Lansoft Trade Kft.",
  "IT support and remote service for subscribers, technical assistance for a phone, cable modem, router, or any of their own devices, through the helpdesk interface, and also by phone."],
  ["Self employed",
  "2010 - 2015",
    "",
  "Web store operation, online sales"],
  ["Machine Operator",
  "2016 - 2018",
  "Teva Pharmaceuticals",
  "Pharmaceutical machine operator."]
];
